# Generated by Django 3.0.3 on 2020-05-27 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataScienceModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('section1', models.TextField()),
                ('section2', models.TextField()),
                ('section3', models.TextField()),
                ('section4', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='DevelopmentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('section1', models.TextField()),
                ('section2', models.TextField()),
                ('section3', models.TextField()),
                ('section4', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='MlModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('section1', models.TextField()),
                ('section2', models.TextField()),
                ('section3', models.TextField()),
                ('section4', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ProgrammingModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('section1', models.TextField()),
                ('section2', models.TextField()),
                ('section3', models.TextField()),
                ('section4', models.TextField()),
            ],
        ),
    ]
