# Generated by Django 3.0.3 on 2020-05-29 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasciencemodel',
            name='footer',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='datasciencemodel',
            name='gist1',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='datasciencemodel',
            name='gist2',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='datasciencemodel',
            name='gist3',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='datasciencemodel',
            name='gist4',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='datasciencemodel',
            name='header',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='developmentmodel',
            name='footer',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='developmentmodel',
            name='gist1',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='developmentmodel',
            name='gist2',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='developmentmodel',
            name='gist3',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='developmentmodel',
            name='gist4',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='developmentmodel',
            name='header',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='mlmodel',
            name='footer',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='mlmodel',
            name='gist1',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='mlmodel',
            name='gist2',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='mlmodel',
            name='gist3',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='mlmodel',
            name='gist4',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='mlmodel',
            name='header',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='programmingmodel',
            name='footer',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='programmingmodel',
            name='gist1',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='programmingmodel',
            name='gist2',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='programmingmodel',
            name='gist3',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='programmingmodel',
            name='gist4',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='programmingmodel',
            name='header',
            field=models.TextField(default=None),
        ),
    ]
